# Generated by Django 4.2.2 on 2023-06-29 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_alter_ticket_manager"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="request",
            new_name="ticket",
        ),
        migrations.AddField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
